#%RAML 1.0 DataType

usage: provides a type that stores material information
description: A simple Material

properties:
  id: string
  mounting: string
  formats:
    type: array
    items: !include Format.dataType.raml
  providers:
    type: array
    items: !include Provider.dataType.raml
  login: string
  rol: string
